version: '2'
services:
  web:
    build: ./server/php
    ports:
     - "80:80"
    volumes:
     - ./app/:/var/www/app
    links:
     - db
     
  db:
    image: mysql
    ports:
     - "3306:3306"
    environment:
     MYSQL_ROOT_PASSWORD: "root" 
     MYSQL_DATABASE: "main"
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
     - db
    environment:
     PMA_HOST: db
     PMA_PORT: 3306
    ports:
     - '8080:80'
  